message="Hello There. My name is Mert Karabacak"
# message=message.upper()
# message=message.lower()
# message=message.title()
# message=message.capitalize()
# message=message.strip()
# message=message.split()
# # message=message.split(".")
# message="-".join(message)
# index=message.find("Mert")
# isFound=message.startswith("H")
# isFound=message.endswith(".")
# print(isFound)
# message=message.replace("Mert","Tavuk")
# message=message.replace("ç","c").replace("ı","i").replace("ş","s").replace("ö","o").replace(" ","-")
message=message.center(50)
print(message)
# print(message[1])
